### ISSUE TITLE
sfera

### ISSUE THREAD

**Issue by FabioZTessitore** [EnricoRuggieroB/helloworld#1]
quando si fanno calcoli e sono presenti valori costanti bisogna fare attenzione al tipo. Python3 effettua la divisione tra int e restituisce un float, ma non è così per tutti i linguaggi. Inoltre, chi legge il codice non sa se c'è un errore oppure era una cosa voluta

**Comment by RuggieroB** [comment]
Quindi, se ho ben compreso, cambio il cast da “int” a “float”, giusto?

**Comment by FabioZTessitore** [comment]
no, il raggio della sfera deve essere int (è un requisito dell'esercizio). Sono le costanti delle formule che vanno cambiate

**Comment by RuggieroB** [comment]
Ho controllato le soluzioni: l’errore è il “.” (punto) dopo “4” e “3”?

**Comment by RuggieroB** [comment]
Il punto dopo 3 e 4?



Inviato da Libero Mail per iOS


sabato 22 dicembre 2018, 09:27 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
si

**Comment by RuggieroB** [comment]
Bene, grazie. Appena ritorno dal San Carlo, provvederò alla correzione e ad aggiungere anche l’Algoritmo per le equazioni di secondo grado.
Buona giornata 



Inviato da Libero Mail per iOS


sabato 22 dicembre 2018, 09:32 +0100 da notifications@github.com  <notifications@github.com>:
