### ISSUE TITLE
secgrado

### ISSUE THREAD

**Issue by FabioZTessitore** [EnricoRuggieroB/helloworld#3]
il problema è la variabile `Rad_-Delta`
E' un nome non valido

**Comment by RuggieroB** [comment]
Corretto, ma mi da ancora l’errore



Inviato da Libero Mail per iOS


sabato 22 dicembre 2018, 22:06 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
che errore? a me funziona

**Comment by RuggieroB** [comment]
Gli stessi errori per cui Le ho scritto.



Inviato da Libero Mail per iOS


sabato 22 dicembre 2018, 22:24 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
il programma gira.
Non dà risultati corretti però.
Ti lascio un po' di tempo per cercare da solo il problema (suggerimento: fai attenzione a cosa viene stampato a video e cerca di capire quale blocco di codice viene eseguito)

**Comment by RuggieroB** [comment]
Grazie!



Inviato da Libero Mail per iOS


domenica 23 dicembre 2018, 11:43 +0100 da notifications@github.com  <notifications@github.com>:
